### ISSUE TITLE
Edition tool 

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1284]
Hello,

I added more than 5 layers in the editing tool and it seems to work despite the indicated limitation.
Does this limitation still exist?

Thx

**Comment by rldhont** [comment]
@Cww7 WHich lizmap version ?

@mdouchin cn you confirm ? I do not remember if we removed this limit.

**Comment by Cww7** [comment]
I am currently using version 3.2.

**Comment by rldhont** [comment]
It seems it has been fixed in lizmap-plugin since version 2.2.0:
* https://github.com/3liz/lizmap-plugin/pull/69

There were 2 issues related:
* https://github.com/3liz/lizmap-plugin/issues/60
* https://github.com/3liz/lizmap-plugin/issues/67

The documentation needs to be updated https://github.com/3liz/lizmap-documentation
@Cww7 can you contribute to the documentation ?
Thanks

**Comment by Cww7** [comment]
There is no indication of limits in the documentation but the comment in the plugin is still there: "You can add to 5 layers in the list ...".

**Comment by rldhont** [comment]
so it's an issue in the plugin

**Comment by Cww7** [comment]
Ok, thanks for following @rldhont
