### ISSUE TITLE
Admin CKEditor for landing page - Allow embedding images

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#1379]
### Is your feature request related to a problem? Please describe

At present, the CKEditor Wysiwig tool does not allow to insert images. This is a key feature for users.

### Describe the solution you'd like

CKEditor 5 provides a package to do so:
https://ckeditor.com/docs/ckeditor5/latest/features/image.html

We should allow the user to upload an image, then place it and resize it if needed.

**Comment by nboisteault** [comment]
@mdouchin @laurentj We first need a way to let users upload images. CKEditor 5 has several way to do so : 
https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html
The easier one to add is the [base64 image upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html).
OK for that ?

**Comment by mdouchin** [comment]
Ok for thé base 64

**Comment by laurentj** [comment]
@nboisteault this image upload adapter is a bit ugly :-( Having `<img src="data:...>` has big issues:

- content into the database can be huge (base64 multiply by almost 2 or 3 times the original size)
- browser cannot put the image in cache. So if the user put 3 HD images in its content (remember, almost all users don't resize their images before integrating them into a web content), the browser download 3 huge images each time the page is displayed

I'm not in favor of this such upload adapter.

I prefer an upload adapter which send the image in the server side. We could store images in a "standard" directory of Lizmap into lizmap/www/. @mdouchin www/documents ? or another new directory ?

Using [Simple Upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html) seems to be the best simple solution.

Using [CkFinder](https://ckeditor.com/ckfinder/] could be the best solution, as the user can resize/crop the image before uploading it.

**Comment by nboisteault** [comment]
@mdouchin @laurentj : 
- we won't save images in database but in an HTML file. I read base64 is on average [33% bigger](https://www.davidbcalhoun.com/2011/when-to-base64-encode-images-and-when-not-to/).
- good point, for cache. But I think we can make the assumption that people will use the landing page to put small logos and in worst case one big picture. We coud document that people should resize their bigger images.

**Comment by laurentj** [comment]
>we can make the assumption that people will use the landing page to put small logos and in worst case one big picture

You can make the assumption, but I don't. In all projects I worked on, where users had to store images, they never resized their images before uploading it. Never. Even they know they should resize them. Because it's a boring task for them : open gimp/photoshop/whatever, open the file, resize the image, save the file under an other name, then indicate this file into the form etc.. 

And I don't want these base64 images on our platform (because of the band-width etc).

The best solution is to propose an interface, allowing to select an image. A JS lib shThen, before uploading it, a JS lib could resize the image if it is larger than a max-size we should specify. The lib could also propose resize/crop features for the user.

base64 image upload adapter is not a long term solution. I know that other solutions need more work, but it's better at the long term. It could be used in the map editor or in any other places into lizmap (like custom modules).

@mdouchin, your thought?

**Comment by mdouchin** [comment]
I was not aware of the cache issue with base 64 images.
I totally agree with @laurentj then.

**Comment by nboisteault** [comment]
Ok I'll go for CKFinder then, to have a powerful image uploader.

**Comment by nboisteault** [comment]
@mdouchin Do we go further than image upload and let users upload documents? This way they could add some documentation for example.

**Comment by nboisteault** [comment]
> @laurentj @mdouchin I need to install the [PHP part of ckfinder](https://ckeditor.com/docs/ckfinder/ckfinder3-php/quickstart.html). Is it ok to put it in /lizmap/www/ or should we use a Jelix controller?

After some thinking, we have to pass through a controller to handle rights, only uploaded files should end in /izmap/www/

**Comment by nboisteault** [comment]
@laurentj could you add SimpleUploadAdapter plugin in our ckeditor5 build please ? Thanks !
