### ISSUE TITLE
Can't visualize data on lizmap master - debian 9.x - Qgis 3.4

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#1472]
Hello lizmap developers
today we tried to upgrade debian/qgis/lizmap  to 9.11/3.4.4/master (via git)

The result is that all maps I creted with qgis 2.18 and 3.4 are not visualized in map canvas.
data are on a postgis server and are correctly loaded in desktop

The lizmap server shows google/OSM base layers, the vectorial layers are in legend but they do not appear in map canvas.

If I open attribute table in lizmap web client data are loaded and I can zoom to the selected record.

What could be my problem?

Thanks
Pietro

**Comment by pcav** [comment]
Did you upgrade the projects?
Cheers.

On 22 January 2020 16:13:19 GMT+04:00, Pietro Rossin <notifications@github.com> wrote:
>Hello lizmap developers
>today we tried to upgrade debian/qgis/lizmap  to 9.11/3.4.4/master (via
>git)
>
>The result is that all maps I creted with qgis 2.18 and 3.4 are not
>visualized in map canvas.
>data are on a postgis server and are correctly loaded in desktop
>
>The lizmap server shows google/OSM base layers, the vectorial layers
>are in legend but they do not appear in map canvas.
>
>If I open attribute table in lizmap web client data are loaded and I
>can zoom to the selected record.
>
>What could be my problem?
>
>Thanks
>Pietro
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/1472

-- 
Please excuse my brevity.

**Comment by pieri70** [comment]
Ciao
yes of course..
But we solved our problem upgrading from Debian 9 to debian 10 and then Qgis server from 3.4.4 to 3.10.x.

Now all seem to run fine, tomorrow I'll test everything.
thanks

**Comment by gioman** [comment]
@pieri70 I have hit a similar issue yesterday, on a Ubuntu Server machine that was not installed by me.

Using LMWC or using the WMS service as published by LMWC I got the layers lagends but no images (not blank images, it was really the GetMap request not going anywhere).

On the same machine a GetMap a direct request to QGIS Server (so not using the WMS from LMWC) worked ok.

After many tries I realized that in LMWC if the URL for QGIS Server was set as http**S** then the described behavior was observed. Weird thing because in general httpS works ok in this machine (also to use LMWC) and httpS can be used in the URL for a direct WMS service (not using LMWC).

I still haven't found how to fix this at a system level, as I don't think is either a bug in LMWC or QGIS Server.

**Comment by pieri70** [comment]
Thanks gioman
As I wrote we solved our problem upgrading from debian 9.x to 10.x.
May be overkill but it worked.

**Comment by gioman** [comment]
> As I wrote we solved our problem upgrading from debian 9.x to 10.x.
> May be overkill but it worked.

I have seen it, I just found curios that the symptoms are identical. Maybe in your case the upgrade was unrelated to the "fix" (maybe you also just use a plain http URL for QGIS Server in LMWC configs?)?

**Comment by pieri70** [comment]
You mean this?
Indirizzo (URL) del server WMS > http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi

I didn't touch this line both in 9.x and in 10.x

**Comment by gioman** [comment]
> You mean this?
> Indirizzo (URL) del server WMS > http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi
> 
> I didn't touch this line both in 9.x and in 10.x

yeah... so it seems that two different things caused the same symptoms. Never mind.
