### ISSUE TITLE
Enable print on load

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#1500]
# Problem

I have set up an instance of lizmap and will only be using it for printing maps. 
What is the easiest or most efficient way to activate the print control on load?

* Is it by overriding the JS
* Or by editing the map.js

**Comment by nboisteault** [comment]
Add a custom JavaScript :
https://docs.lizmap.com/current/fr/publish/advanced_lizmap_config.html#adding-your-own-javascript

**Comment by Gustry** [comment]
Hi @NyakudyaA, nice to see you here ;-)

What is your case exactly? Is-it Atlas based maps or just a layout?

You shouldn't edit `map.js` because it's part of the Lizmap source code. If you do an update, you will loose your configuration.

Adding Javascript is the best, the link in English in the new version : https://docs.lizmap.com/next/en/publish/customization/javascript.html

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA, nice to see you here ;-)

Hi @Gustry Nice to hear an answer from you as well
> 
> What is your case exactly? Is-it Atlas based maps or just a layout?

It is just layout based.
> 
> You shouldn't edit `map.js` because it's part of the Lizmap source code. If you do an update, you will loose your configuration.
> 
> Adding Javascript is the best, the link in English in the new version : https://docs.lizmap.com/next/en/publish/customization/javascript.html

Thanks
