### ISSUE TITLE
base layer - order by name

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1510]
hi

![imagem](https://user-images.githubusercontent.com/10053874/74173919-e7d42980-4c2a-11ea-8282-84c153ef321d.png)

the base layers have a random order
it's good to have the layers order given by the plugin

thanks

**Comment by Gustry** [comment]
Hi @josemvm 

We really appreciate your early testing and feedbacks on LWC. You are spotting bugs in the early stage of development and this is appreciated to have beta testing.

I invite you to read the blogpost from Nyall Dawson, the main contributor in core QGIS : https://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/
Lizmap and QGIS is slightly different, because QGIS is not owned by a company but we are trying to make Lizmap an opensource project with a community on github.

Please read the latest changelog about the 3.5 release : https://www.3liz.com/news/lizmap-web-client-3-5.html
You will notice that new features are :  
- either coming from the GitHub opensource community (contribution from Florian, Igor...)
- or paid by customers. Their logo is showed and paid features are listed.

At 3Liz, we do spend times on non-paid features in Lizmap Web Client, refactoring code, doing our manual testing which is invisible for end users like you. You can read [our blog post](https://www.3liz.com/blog/rldhont/index.php?post/2021/03/18/On-our-way-to-quality) how we are trying to improve testing in Lizmap. That's why I'm adding the label "sponsor or PR needed".

**Comment by josemvm** [comment]
hi @Gustry 

thank you very much to point me to the excellent writeup from Nyall Dawson!

i really understand your point of view and i clearly assume my natural tendency to try to shape lizmap a little bit according to my expectations (as in everything in life) - sorry for that...

i really appreciate the lizmap project in particular and all other work and technical skills of the 3Liz team!- thank you.

it' s a great pleasure to me to help the project and community, doing some tests and reporting the results :smiley:

**Comment by nboisteault** [comment]
Now w/ Lizmap 3.7, you define a `baselayers` group and put your layers in it in the order you want.
