### ISSUE TITLE
Impossible to have several docker running for tests

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1550]
### What is the bug?
I tried to run docker in `tests/` and it works like a charm. But i tried to run an second instance in an other lizmap and it conflicts.

**Comment by laurentj** [comment]
Which conflicts do you talk about?  Network port conflicts? or docker containers conflicts ?

For docker containers conflicts, I give a project name to docker-compose : commit 9abd4b894d702ccffe2f795034d972ab9eb2f927 .

Before updating the sources (or remove by hand the parameter I added), stop all containers `./run-docker stop`, then `./run-docker rm`. Then update sources or restore the new parameter, and you can `./run-docker up`.

I should improve the script in order to setup easily a project name, so in each instance, you could give a different project name, and then no conflicts with images.

For Network port conflicts, the first solution is to not run all instances at the same time. The second solution is to improve the configuration so we could indicate (with environment variables ?), port to use for each containers.

**Comment by nboisteault** [comment]
It is not network conflict but docker container one.
