### ISSUE TITLE
Any suggested tool (easy) to display large data amount?

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#1577]
Hello
I'm not skilled in developing code.
Is there some "easy" solution to display data related to a given lizmap layer?

Example, a point layer and a large postgres dataset with sampling on each point in this layer.
Each point has many samples (different time) and each sample has many measures for different parameters.

Do you suggest some easy developing tool?

Thanks
Pietro

**Comment by nboisteault** [comment]
You can use the attribute table in Lizmap. You can display data with relational links.

**Comment by pieri70** [comment]
Do you think it's feasable with huge amount of data?
I mean, a single station (point) could have thousand of associated records and there are may be 500 single stations..
For what I'we seen right now data table is a little slow loading attribute of 400 points, 10 columns table without any relation..
I think lizmap loads the whole dataset before showing attribute table, isn't it?

**Comment by Gustry** [comment]
Can you try with a relation? 
And disable the display of the attribute table for the child layer. Only access the layer from the parent layer with a relation.

**Comment by pieri70** [comment]
I'll make some test..
Thanks

**Comment by mdouchin** [comment]
If the data is not sensitive, you could also share it and we could help you. Some hints

* Use the dataviz tool, combined with relations, to display plots with sampling data in the popup of each point. Scatter plot use webgl, so the display performance should be ok
* In the attribute table, you should indeed not show the table of the big dataset, because indeed lizmap does not -yet- use pagination (because the support of OFFSET did not exist in QGIS Server some time ago), so the perfs would be bad. You can try as @Gustry suggested to use relations betwee point (parent) and samping data (child) 

If you have some needs and resources, you could help use add the support of pagination in the attribute table, so that any dataset could be used inside Lizmap :-)

**Comment by pieri70** [comment]
Thanks @mdouchin 
I will prepare a subset of data to send you

As regard to relations, does this solution improve data loading?
I mean data are loaded as I expand relation and not all together like in table data?

Pietro
