### ISSUE TITLE
HTML code in fields value

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#164]
Hi,

I have a field wich is a link to a PDF. It works OK. These are the steps I followed:

I create a new virtual field:

![sin titulo1](https://cloud.githubusercontent.com/assets/12136796/8076834/c00eed34-0f50-11e5-88bb-911882cfd0dc.png)

In the field's Edit Widget I select "File Name":

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/8076903/4e653d86-0f51-11e5-8877-15ea88bee59f.png)

In lizmap's popup the link is shown as:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/8076929/80278554-0f51-11e5-8c49-7c581da1b917.png)

Instead of the text, i would like to see a PDF icon, for example, so people can figure out that if they click there they are going to download a PDF.

<img src="http://www.aspose.com/blogs/wp-content/uploads/2011/11/Adobe-PDF-File-Icon.jpg" alt="PDF" height="28" width="28">

I imagined there was going to be some Edit Widget in QGIS that would allow to insert plain HTML or something like that and then, in field calculator, I would add something like:

' < a href="/media/PDFs/'|| "Numitinerario"  ||'.pdf" > < img src="http://www.aspose.com/blogs/wp-content/uploads/2011/11/Adobe-PDF-File-Icon.jpg" alt="PDF" height="28" width="28" > < / a> '

(I inserted some extra spaces so that the text is not understood as html here)

Is this possible to achieve somehow in lizmap?

**Comment by 3liz** [comment]
Hi,

You can do this 2 ways:

* configure a "Tooltip" for the vector layer ( in the vector layer properties dialog, tab tooltip ) : this way, you should be able to use the tooltip map tool in QGIS to preview the result.  Then, Lizmap will use this configuration to display the popup (instead of the default table)

* configure the "advanced" popup in Lizmap, as described here : http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#advanced-popup-configuration-html-format
