### ISSUE TITLE
Change of the e-mail notifications content

### ISSUE THREAD

**Issue by bgisb** [3liz/lizmap-web-client#1694]
### Description
Hi! Could you please advise mi if it is possible to change the e-mail notifications content?
By default, I receive information in English, although I use lizmap in a browser with other locales.

Can I change the content of the e-mails on the server? I would like to translate them.

### Environment

 - Lizmap version: 3.3.4-pre

**Comment by rmarzocchi84** [comment]
I think it depends on the language of your server. 

https://docs.lizmap.com/current/en/install/linux.html#configure-locales

**Comment by rmarzocchi84** [comment]
I ask confirmation of @Gustry or other main developers.. 

I like to change the style of the mail

![image](https://user-images.githubusercontent.com/4061154/102253565-c3f70980-3f07-11eb-98da-deba6dab0185.png)

e.g the link, new line, etc,  

Where I can find the code to change in order to create a pull request? 
If I change the english it affects also the Transifex project but I do not really undestand how can I give my modest contribute 
There is a way to change code both for 3.3.X and 3.4.X branches?
