### ISSUE TITLE
Adding files/images for features in lizmap

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#175]
Hi,

I would like to be able to save a photo for a feature in the map.

I guessed I had to configure the FTP tab in lizmap-plugin. I did it.

Then in QGIS, in the chosen field I selected "File name" widget that should add a file chooser dialog. in lizmap a started the edition on the layer, I selected the feature, I clicked on modify and in the form the comboboxes and checkboxes are working ok but in my "File name" field a edit text widget is being displayed. 

I also tried with the "Photo" Edit Widget with same result in lizmap...

Is this possible to do in lizmap?

**Comment by mdouchin** [comment]
Hi
You do not need to configure and use the FTP tab of lizmap plugin. It is always better to use your prefered FTP client (FileZilla or FireFTP, etc.).
The support for sending Photos and Files has been added in the "master" and will be available in future Lizmap Web Client 3 (soon to come !). It is not yet possible with Lizmap 2.10

**Comment by valeriodeluca** [comment]
I look forward lizmap 3 for online photo editing, if I can help with the development or testing I'm happy to do it ciao

**Comment by rldhont** [comment]
Hi @valeriodeluca, you can test the master and propose some code. Your help is welcome.

**Comment by valeriodeluca** [comment]
ok I do

**Comment by valeriodeluca** [comment]
Sorry I'm a little mule, but I don't find the master, have you a link? tks
cheers

**Comment by rldhont** [comment]
hi @valeriodeluca just here https://github.com/3liz/lizmap-web-client:
you can make a git clone or download a zip file.

**Comment by valeriodeluca** [comment]
ok tks :)

**Comment by cristomoya** [comment]
Hey there; I've been testing the feature to upload images and seems to work well .

Save the image path but no picture

My version is the 3.0beta1

**Comment by valeriodeluca** [comment]
hi cris, u mean
1 u shot a photo by phone and then upload it automatically in lizmap (by
browser) or
2 u give the path in shapfile field and upload photo apart?
tks, best, valerio

**Comment by cristomoya** [comment]
I refer to the first option, up from iphone. In the database I have a field with the path of the picture. Not whether it is the right thing to do
Thank you

**Comment by valeriodeluca** [comment]
ok...the database where is? on phone or on server? I use digital ocean
server
Il 16/dic/2015 20:27 "cristomoya" <notifications@github.com> ha scritto:

**Comment by cristomoya** [comment]
On server, I use apache2 on OSGEOLIVE

**Comment by mdouchin** [comment]
Hi all,

This issue shows that there is a lack of proper documentation for this feature. Please be patient, as this feature has been added recently, and Lizmap Web Client 3 in to yet available (only in beta version).

To achieve this goal, you need to follow these steps

* Configure edition for the layer, with one or more fields with the **edit type** "Photo" or "File". For example, let say the field name is "photo"
* Create a folder at the root of the QGIS project file : **media/** and a subfloder **media/upload** (obviously you need to do that locally in your computer and server side ).
* Give Apache user (usually www-data ) **write permission** on the upload folder, so that it can create files and folders in media/upload : 
    
    chmod 775 -R media/upload && chown :www-data -R media/upload

* Check you **php.ini** to see if the variables **post_max_size** and **max_upload_size** are correctly set (by default, php only allows uploading files up to 2 Mo )

Lizmap will then create folders to store the data, depending on the layer name, field name, etc. For example, a file would be stored in this folder

    media/upload/PROJECT_NAME/LAYER_NAME/FIELD_NAME/FILE_NAME.EXT

For example

    media/upload/environment/observations/species_picture/my_picture.png

Obviously you will be able to display this image (or any other file) in the popup, as it will be stored in the media folder : see http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#use-in-popups

**Comment by gioman** [comment]
Using osgeo live is likely a writing permission issue.

**Comment by cristomoya** [comment]
thanks , I 've tried it and it works really well

**Comment by cristomoya** [comment]
Hey there:
I've been testing the application with the iphone and I have found a mistake. When the camera application is used to capture the photo does not work and does not come up photos. But when a photo downloaded or made another application is used if you do

**Comment by rldhont** [comment]
Documentation is in progress

**Comment by pcav** [comment]
Done.

**Comment by gmusumeci** [comment]
Hey there; I've been testing the feature to upload files.
It save the file path into my server folder but no pdf

My version is the 3.0.1 on Xubuntu.

I have the following error

016-07-20 10:07:55	192.168.16.174	strict	2016-07-20 10:07:55	[2048]	Only variables should be passed by reference	/var/www/lizmap-web-client-3.0.1/lizmap/modules/lizmap/controllers/edition.classic.php	810

2016-07-20 10:07:55	192.168.16.174	strict	2016-07-20 10:07:55	[2048]	Only variables should be passed by reference	/var/www/lizmap-web-client-3.0.1/lizmap/modules/lizmap/controllers/edition.classic.php	810

2016-07-20 10:07:55	192.168.16.174	notice	2016-07-20 10:07:55	[8]	Undefined offset: 0	/var/www/lizmap-web-client-2.12.6/lizmap/modules/lizmap/controllers/edition.classic.php	1184
