### ISSUE TITLE
Parameters hideSensitiveServicesProperties and registrationEnabled incompatibility

### ISSUE THREAD

**Issue by Bray-N** [3liz/lizmap-web-client#1879]
Hi,

Some lizmap (3.3.10) users are not able to change the "registrationEnabled" ("Autoriser les visiteurs à demander un compte") parameter to "On" via the admin interface.
After form validation, the parameter is still displayed to "Off".

This happen only when the hideSensitiveServicesProperties parameter (lizmapConfig.ini.php) have been defined to "1".
Same result if the [mailer]/webmasterEmail is already defined in liveconfig.ini.php (with "hideSensitiveServicesProperties" On, this field can't be modified).

Thanks

**Comment by laurentj** [comment]
If the configuration parameter `webmasterEmail`, in the section `mailer`, of localconfig.ini.php or liveconfig.ini.php  is not defined or has the default value (defined as `root@localhost` into mainconfig.ini.php), you cannot enable the registration, because, if the email is not set, lizmap cannot obviously send email.

When hideSensitiveServicesProperties is `1`, you cannot change the email, and so, if the email is not set, registrationEnabled stays with the off value. 

The issue here, in fact, is that we should deactivate the field registrationEnabled in that case, and display a message to the user, explaining that he cannot change the value because the webmaster email is not set. We will fix that.

The solution for you, if you have `hideSensitiveServicesProperties` set to `1`, is to set the webmasterEmail configuration parameter into localconfig.ini.php (do not change mainconfig.ini.php! [see why in the documentation](https://docs.lizmap.com/current/en/install/configuration.html)). For example:

```ini
[mailer]
webmasterEmail=lizmap-admin@acme.example.com
webmasterName=Lizmap administrator
```
