### ISSUE TITLE
Background layer is shown in legend in print mode.

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#189]
Lizmap 2.11
I've created a map with an osm-mapnik background layer which is in an hidden directory as described in documentation.
When I print my composer in lizmap the background is visible but its name and group's name are also visible in the legend part.
![bug impression](https://cloud.githubusercontent.com/assets/2145040/9087963/018fa726-3b8e-11e5-9ebb-b80808045cb4.jpg)

**Comment by jaitor1** [comment]
Can you explain me how did you manage to print the osm-mapnik?

I am trying to do the same with google-street base layer but after 2 hours I am not capable of making it work. I added a layer called google-street as mentioned in the documentation. I created a group named "hidden" as mentioned in documentation (what I could understand in French doc). 

But the base layer is not displayed in the printed PDF....

What should be the configuration in lizmap plugin both for the "hidden group" and the google-street layer?

Any other configuration in QGIS project is needed?

My google-street layer is added using the "OpenLayers Plugin" for QGIS, could this be the problem?

I am also in Lizmap 2.11.

**Comment by rldhont** [comment]
Hi @jaitor1,

Here is the english documentation: http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#allow-printing-of-external-baselayers

Don't use "OpenLayers Plugin" for this feature and you can print Google if you have paid the licence.

**Comment by jaitor1** [comment]
Hi @rldhont ,

I think I am not understanding very well how this feature works.

As mentioned in http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#hide-layers I created the xml file and added  to my QGIS project as a new raster layer. I use osm-mapnik because it is free, Google layer's would need me to pay to be able to use it as you said.

I renamed the layer as osm-mapnik and added it into a "hidden" named group as it is mentioned in the doc: http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#allow-printing-of-external-baselayers

I can see the tiles correctly in QGIS:

![image](https://cloud.githubusercontent.com/assets/12136796/9460980/e35c9796-4b0a-11e5-8668-6c649a93bf39.png)

I publish the new layer in WCS capabilities which I don't know if it is needed:
![image](https://cloud.githubusercontent.com/assets/12136796/9461016/2cd8778c-4b0b-11e5-949f-8c0ce85244bb.png)

Lizmap plugin is as follows for the osm-mapnik layer:
![image](https://cloud.githubusercontent.com/assets/12136796/9461032/56e02f20-4b0b-11e5-910d-96ce8c128271.png)


And as follows for the hidden group:
![image](https://cloud.githubusercontent.com/assets/12136796/9461051/6b600fec-4b0b-11e5-9c68-cbdca65dc38d.png)


When I print in lizmap no background image is displayed:
![image](https://cloud.githubusercontent.com/assets/12136796/9461112/fda6fa82-4b0b-11e5-9e43-15cdd2aa96c1.png)

![image](https://cloud.githubusercontent.com/assets/12136796/9461122/0bd6cfb0-4b0c-11e5-930c-a1dd13d1de2d.png)

**Comment by rldhont** [comment]
Hi @jaitor1, thanks for your reply which help me to understand your need.

If you want to replace *Google* base layer by *OSM* in your print renames the layer *osm-mapnik* by *google-street*. To print a base layer based on an external web service, you have to put a layer in the QGIS project with the layer name used in OpenLayers. For example, to print OpenStreetMap you have to put a layer osm-mapnik in your QGIS project. If it doesn't work, it's an issue.

**Comment by jaitor1** [comment]
Hi @rldhont , the layer added in the QGIS project needs to be a raster image or can, for example, be a new empty SHP? 
So the raster (xml) layer I have used is not valid to be able to print osm-mapnik later?

Is the rest of configuration, ok?

I think it is not an issue because @nboisteault managed to print the osm-mapnik as you can read in the first post of this issue. I must have something wrong in my config...

I'll make some other test and see if I can make it work.

Thanks for your help @rldhont

**Comment by nboisteault** [comment]
As far as i understand, the only way to hide the background layer in the legend is to disable the automatic update and then disable the layer in QGIS print composer but you lose the benefit of automatic update...
Maybe it should be added in QGIS a way to define a base layer which would not be visible in legend.

**Comment by rldhont** [comment]
@jaitor1 The layer to replace external bacelayer is what you want: vector or raster.
The raster (xml) layer you have used is valid for osm-mapnik, if the user choose OpenStreetMap as baselayer in the web UI.

**Comment by rldhont** [comment]
@nboisteault In the QGIS print composer you have to:
* disable the automatic update
* remove the baselayer from the legend
* activate filter

**Comment by jaitor1** [comment]
@rldhont  With the configuration I have mentioned you in my previous post's snapshots and, as you said, selecting OpenStreetMap as baselayer in Lizmaps' Web UI I still don't see the background in the PDF...do you see anything that may be wrong in the config. in the snapshots?

**Comment by nboisteault** [comment]
@rldhont It works, thank you.
