### ISSUE TITLE
Why doesn't Lizmap bundle layers in QGIS Server WMS requests?

### ISSUE THREAD

**Issue by cxcandid** [3liz/lizmap-web-client#2335]
If I configure multiple QGIS project layers without grouping, it would be beneficial if Lizmap performs only a single WMS request instead of many individual ones. There is a big difference in label positioning. If all layers are bundled into a single WMS request, QGIS Server will respect the label blocking settings and prevents labels being overlapped by features.

Is there any specific setting to enable layer bundling in WMS requests? 
Putting layers in a Lizmap group is no option, because we need to toggle individual layers.

**Comment by mdouchin** [comment]
Indeed it has been a while we would like to propose such a feature, but there is a lot of work to do, since some Lizmap Web Client tools need to have a single OpenLayers layers to work.

It would benefit a lot for some uses cases, but I also think it should be an option (for example the layers or grouped use with the server tile cache on, i.e in WMTS,  must stay as single layers)
