### ISSUE TITLE
Attribute table is not displayed for a postgis layer

### ISSUE THREAD

**Issue by slarosa** [3liz/lizmap-web-client#239]
I cannot see the attribute table when adding a postgis layer with over 15K rows, the layer is displayed properly over the map but the attribute table is empty. Applying a filter on the qgis side (with about 800 rows) all works fine. Is there a limit of rows that can be displayed? Is this a known issue?
My project has sensible data so I cannot share it.

It occurs with QGIS master version and LWC 3.0.

**Comment by JogicPogic** [comment]
I support! I have the same problem.

**Comment by slarosa** [comment]
More info:
GetFeature Request [0] looks good I get a status code 200 OK. 
```
?repository=myrepo&project=myproject&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=mylayer&OUTPUTFORMAT=GeoJSON&GEOMETRYNAME=extent
```
Opening the above URL in a browser I get the whole GeoJSON file but nothing appears in Data window.

**Comment by rldhont** [comment]
Thanks for this review.
Did the issue be with QGIS Server master or with other version ?
Did you test the GeoJSON in a JSON or GeoJSON reader/validator ?

**Comment by slarosa** [comment]
@rldhont I tested with http://jsonlint.com/ and it results as a valid JSON.
I am testing with QGIS Server master version.

One more info: setting ```MAXFEATURES=2100``` in ```map.js``` does not work while ```MAXFEATURES=2000``` has worked. It seems like ~2K is the limit. (just a test) 

Also, when this issue will be fixed, I would like suggest to insert a loading gif icon to do aware the user about the table is being loaded, big table may take a long time.

**Comment by rldhont** [comment]
H @slarosa and @JogicPogic, did you test in LWC 3Beat3 ?

**Comment by slarosa** [comment]
@rldhont tested 3.0b3 (fb79094), unfortunately the issue still persists for me :(

**Comment by haubourg** [comment]
Hi, same issue here with yesterday's master. 
Cheers Régis

**Comment by haubourg** [comment]
tested with a 2786 rows dataset from postgis. json is import correctly in qgis though (with no geometry)

**Comment by haubourg** [comment]
reducing table to less than 2000 rows works here

**Comment by mdouchin** [comment]
Since QGIS Server did not have a way to get only a set of feature ( via an OFFSET parameter) before 2.14, we chose in first approach to get the whole content of the layer data and process it in javascript afterward.

@rldhont added recently the possibility to add an OFFSET in WFS request. We will then be able to paginate the attribute table content server side

At present, it depends a lot of
* the layer complexity, 
* the number of fields displayed in the attribute table (try to keep only 3 or 5 fields as a test (by unchecking the WFS checkbox in QGIS vector layer fields tab)
* the server capabilities.

I tried in my laptop ( only 4Go RAM and 4 proc 2.20Ghz) and I can open an attribute table with 80000 features and about ten fields.

**Comment by rldhont** [comment]
A new feature in 3.1, will give you the ability to filter the table by map 5e736a01c2cbf739c737b8e8c1d54c41d23d4f0f

**Comment by rldhont** [comment]
@slarosa can you provide some feedbacks ?

**Comment by slarosa** [comment]
@rldhont I will give it a try tonight testing the release 3.2

**Comment by slarosa** [comment]
@rldhont I done my test on release_32 branch and it has worked fine, even without the option to fetch data only within map extent. I done a test with a postgis table with over 18K features without any issue. Thanks and sorry for answering late.
