### ISSUE TITLE
[Bug]: Printing tool - map area on printed page is different from area highlited on webmap with printing tool

### ISSUE THREAD

**Issue by lucaplz** [3liz/lizmap-web-client#2762]
### What is the bug?

After upgrade to 3.5.1 (from 3.4.9) We noticed that printed map scale is now correct (thank you!) but map extent on printed layout is not the same as was highlited in webmap with printing tool.
![lm_layout_area](https://user-images.githubusercontent.com/64898041/153221123-e03ea778-63ac-488f-86f6-1bed74820588.png)

### Steps to reproduce the issue

Follow the usual procedure to print a map.

### Versions

**Versions :**

* Lizmap Web Client : 3.5.1
* Lizmap plugin : 3.7.1
* QGIS Desktop : 3.16.16
* QGIS Server : 3.16.16

### Operating system

Debian 11.2

### Browsers

Firefox, Chrome

### Browsers version

Firefox 91.5.0esr, Chrome 98.0.4758.80

**Comment by mdouchin** [comment]
Since 3.5.x, we have indeed changed the print behaviour: we always print in the **QGIS project projection**. Before, we printed in the **web map projection**.

In LWC, depending on the status of external baselayers:

* the web map is displayed in the projection of your QGIS project if no external baselayers are used
* the web map is displayed in Pseudo-Mercator `EPSG:3857` if there is at least one external base layer (since all these baselayers are meant to be displayed on this projection

In your case, your web map display projection is `EPSG:3857` and the printed page is rendered in your project projection `EPSG:3003`, which explains why the rectangle chosen in the web map is not fully respected.

We decided to respect the **chosen scale** and not the rectangle.
