### ISSUE TITLE
[Question]: qgis/edition folder in documentation but not on the repository

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#3006]
### What is the question?

Hello
today I tried to install LWC 3.5 via Git clone on a test directory in debian
Then I followed the guide on how to setup/upgrade from another version
Here is the guide
https://docs.lizmap.com/3.5/en/install/upgrade.html

It writes:
Redefine the rights to the application files
cd /var/www/$MYAPP-$VERSION
chown :www-data temp/ lizmap/var/ lizmap/www lizmap/install/qgis/edition/ -R
chmod 775 temp/ lizmap/var/ lizmap/www lizmap/install/qgis/edition/ -R

but there isn't any edition folder in lizmap/install/qgis/
Where is this folder or what is its purpose?

Thanks

### Versions

LWC 3.5 

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.18

### Operating system

debian 10.12

### Browsers

Chrome

### Browsers version

Opera latest

**Comment by Gustry** [comment]
> today I tried to install LWC 3.5 via Git clone

You shouldn't use the source code from **git**, but better to use ZIP provided in releases, otherwise, you need to **build** the application.

Please have a look to the link : https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#get-the-source
https://github.com/3liz/lizmap-web-client/releases

On the link you gave, I can read : 

> Get the Lizmap archive (by downloading an archive or by doing a git clone/pull)

I will go and update it. Thanks.

**Comment by Gustry** [comment]
Fixed in the documentation : https://github.com/3liz/lizmap-documentation/commit/69719ed0652a36e9911f0fab89edf9000939594f
