### ISSUE TITLE
[Bug]: popup - source: QGIS HTML maptip

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#3379]
### What is the bug?

LWC doesn't show image in popup.

QGIS HTMLMap Tip
`Photo<img src="file://[% @project_home %]/[% "imagem_liz" %]" width="450" />`
![imagem](https://user-images.githubusercontent.com/10053874/208958915-717f25ea-a1de-4391-9cf8-756811884393.png)

LWC Popup
![imagem](https://user-images.githubusercontent.com/10053874/208959137-27b0c257-c035-493c-a30b-669a25e922ce.png)

### Steps to reproduce the issue

...

### Versions

**Versions :**

* Lizmap Web Client : 3.5.8-pre.5560
* Lizmap plugin : 3.9.8
* QGIS Desktop : 3.16.16
* QGIS Server : 3.16.16
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

108.0.1

**Comment by josemvm** [comment]
exemple of the field content `[% "imagem_liz" %]` : media/SIG-Redes_imagens/a_as_791.jpg

**Comment by Gustry** [comment]
Please show us the generated string, the source of the image in your webbrowser.

@josemvm This kind of expression will work only if your webbrowser is located on the server, or you are using a kind of network storage ?

Is the path accessible from your computer ?

**Comment by josemvm** [comment]
>Please show us the generated string, the source of the image in your webbrowser.

src="file:///var/www/html/lizmap_web_client/lizmap/install/ma/media/SIG-Redes_imagens/a_as_800.jpg"

> @josemvm This kind of expression will work only if your webbrowser is located on the server, or you are using a kind of network storage ?

i also tried with a webbrrowser located on the server and it doesn't work too
the image is stored on my qgis server and is accessible like here for thumnail image (it's the same field):
![imagem](https://user-images.githubusercontent.com/10053874/208963946-31daa854-1f68-46fa-a10a-7437439c9425.png)

>Is the path accessible from your computer ?

yes

**Comment by Gustry** [comment]
IMHO, it's very strange use-case because your server filesystem **must** be accessible from your webbrowser for your thumbnail to work. Why not using the HTTP protocol ? It's not a web application in your case.

If you really want this behavior, IMHO, you should make the link working in your webbrowser `/var/www/html/lizmap_web_client/lizmap/install/ma/media/SIG-Redes_imagens/a_as_800.jpg` first then you generate the path needed.

What is the path of your thumbnail working ?

Some documentation : 
Non-local web pages [cannot access local files](http://blog.chromium.org/2008/12/security-in-depth-local-web-pages.html) in any modern web browser.

I won't dig more in this question.
