### ISSUE TITLE
[Bug]: legend display

### ISSUE THREAD

**Issue by JBL034** [3liz/lizmap-web-client#3510]
### What is the bug?

none of the legends of the project layers are displayed correctly: the description is missing for each of the symbols.
Is there a setting that I forgot?...

Qgis legend:
![image](https://user-images.githubusercontent.com/31103023/220684669-7ba581bd-a256-4bac-9e11-1c387162a46b.png)

Lizmap legend:
![image](https://user-images.githubusercontent.com/31103023/220684858-79d1a22d-6508-4a0c-9750-8a7fa494d5d5.png)

prototype de la carte: https://ewatch-carto.pro/lizmap/index.php/view/map/?repository=cartomada&project=DINAMAP-JBL-3-10

### Steps to reproduce the issue

see above

### Versions

QGis 3.18

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu

### Browsers

Firefox

### Browsers version

Firefox 109

**Comment by Gustry** [comment]
Please follow the issue template with the requested versions in the Lizmap plugin. What are your versions of server and desktop ?

**Comment by JBL034** [comment]
lizmap client: 3.5
lizmap server: 3.5.7
QGis server 3.10

**Comment by Gustry** [comment]
>  QGis server 3.10
> QGis 3.18

I don't have any idea about the problem. Maybe a project written with QGIS Desktop 3.18 can not be read well by QGIS Server 3.10, because you are in the future from a QGIS server 3.10 point of view when reading the project. We always recommend using the **same** version between server and desktop. Or at least QGIS server in front of QGIS desktop. Not the reverse like here. It's definitely an issue.

Lizmap Web Client 3.6 adds some warnings when projects are generated ahead of QGIS server version.

Please reopen when you have updated your server if the problem remains.

**Comment by JBL034** [comment]
merci de votre réponse, je suis au Cirad Montpellier, on peut s'appeler rapidement ? jean-baptiste.laurent@cirad  / 04 67 61 58 97
