### ISSUE TITLE
[Question]: Compatibilité Multiauth - Lizmap web client 3.6.1

### ISSUE THREAD

**Issue by relaire** [3liz/lizmap-web-client#3543]
### What is the question?

Bonjour
J'ai l'habitude d'utiliser le module MultiAuth sur une serveur Lizmap (v3.5).
Je fais des tests sur un nouveau serveur lizmap (3.6.1) et je n'arrive plus a activer le module MultiAuth
Quand je remplace

```
;driver=ldapdao -> driver=multiauth
```

J'obtiens une erreur 500 à l'authentification, et dans le fichier log

```
Class 'Jelix\MultiAuth\ProviderAbstract' not found /var/www/lizmap-web-client-3.6.1/lizmap/lizmap-modules/multiauth/plugins/multiauth/ldap/ldap.multiauth.php 21
```

La configuration LDAP ayant pas mal évolué dans cette nouvelle version de Lizmap, ma question est de savoir si le module Multiauth est toujours compatible.
Merci
Renaud

### Versions

3.22

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.16

### Operating system

debian 11

### Browsers

Microsoft Edge

### Browsers version

110

### Relevant log output

```shell
Class 'Jelix\MultiAuth\ProviderAbstract' not found /var/www/lizmap-web-client-3.6.1/lizmap/lizmap-modules/multiauth/plugins/multiauth/ldap/ldap.multiauth.php 21
```

**Comment by Gustry** [comment]
Checking the changelog of the latest release on 3.6.2 : https://github.com/3liz/lizmap-web-client/releases/tag/3.6.2

> Fix issues in the installer, when installing external modules

and also

> Script install/migrate_from_3_5.sh to make it easier to migrate from Lizmap Web Client 3.5

and other bugfix. I'm not sure if it's related, but anyway, better I think to test and install the latest release available.

**Comment by josemvm** [comment]
hi @laurentj 

i'm using LWC 3.6.2

===
when i run the `composer require "jelix/multiauth-module"` command i get this information:

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.2 for jelix/multiauth-module
./composer.json has been created

Loading composer repositories with package information

Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/

Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing jelix/multiauth-module (v1.2.0): Loading from cache

Writing lock file
Generating autoload files

===
when i run the `php lizmap/dev.php module:configure multiauth` command i get this error:

[error] Unknown module multiauth


can you help me please?

my goal is to continue using the multiauth-module.
i think i have to disable the jcommunity-module due to conflict between both modules

thanks in advance

**Comment by laurentj** [comment]
I made some patch into the multiauth module and into Lizmap. The problem will be fixed into Lizmap 3.6.3 which will be released this week

**Comment by rmarzocchi84** [comment]
@laurentj can you give us some instruction to install multiauth module? https://docs.lizmap.com/3.7/en/install/ldap.html explain only ldap but probably creates a conflict with multiauth module 

we try also the following intstuctions but it doesn't works   https://github.com/jelix/multiauth-module/blob/master/LDAP.md

**Comment by josemvm** [comment]
@rmarzocchi84 you can see here https://github.com/jelix/multiauth-module/blob/master/INSTALL_INTO_LIZMAP.md

**Comment by josemvm** [comment]
what's your os and os version?

**Comment by rmarzocchi84** [comment]
> [@rmarzocchi84](https://github.com/rmarzocchi84) you can see here https://github.com/jelix/multiauth-module/blob/master/INSTALL_INTO_LIZMAP.md

The configuration /installation do not give any error, but the lizmpa instance is unaivalable and I have the following line in the error log:

`jDb profile: driver is missing	/home/procedure/mappenew3/lizmap/vendor/jelix/jelix/lib/jelix/db/jDbParameters.class.php`


- OS Ubuntu 22.04
- LWC 3.7.15

**Comment by relaire** [comment]
I have the same problem with version 3.8. However, it works fine in 3.7.6.
