### ISSUE TITLE
[Question]: Numeric form filter takes only integers

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#3712]
### What is the question?

Numeric form filter takes only integers, which is not optimal but it is usable in cases when you have a greater interval. But in cases when the interval is between 0 and 1, it cannot be used at all. Sliders are blocked, also manual input gives input error (numbers are tuned into red).

### Versions

**Versions :**

* Lizmap Web Client : 3.6.4
* Lizmap plugin : 3.14.0
* QGIS Desktop : 3.28.6
* QGIS Server : 3.28.6
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : v1.5.2

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Microsoft Edge

### Browsers version

Firefox 113.02, Edge 114.0.18....

**Comment by tethysgeco** [comment]
Hi, we are working with this asset:
•	Postgres db
•	Qgis server 3.28 with Lizmap 3.6.4
We added filter of numeric type on fields that are double precision or numeric (max and min values are taken from the same field, the primary key is exposed as wfs); the result is the following.
Before applying filter (max and minimum values are correct):
 
![immagine](https://github.com/3liz/lizmap-web-client/assets/23027624/34a8de3c-5a3a-4ac2-b934-82f1bde8515c)

After we set a minimum value= 380, both max and min are wrongly resized as this (the same behaviour is shown if we digit a decimal value, e.g. 380.6):
 
![immagine](https://github.com/3liz/lizmap-web-client/assets/23027624/75078240-e4ec-469e-921f-dd1b6f69f04b)

This result is really dangerous because it seems that the filter is working but in the map we can’t see the real maximum values (470).
Is this a bug? Should numeric filter be used only on integer type? In this case, please note that both in the documentation and in the plugin the reference to “integer” and not generically to "numeric" should be reported.

Thanks

**Comment by mind84** [comment]
@tethysgeco,
this happens because of the filter step, wich is set by `default to 1`. Thus, if the difference between the `max` value of the range and the `min` value of the range is not an integer, the slider fails to split the entire range of values into an integer number of ranges and try to adapt the min/max value to a couple of number that can be handled properly by the slider itself.
To obtain the desired behavior and ensure the visibility of the entire range of data, the minimum step value of the slider must be exactly equal to the `number precision` of your dataset. I think the default value of the step equal to 1 is because it is not possible to establish in advance the number precision of a generic dataset.
To solve the issue it is possible to act on the slider configuration via JavaScript once the page is loaded, and this can be done in a couple of ways:

1) If you are fully aware of the maximum number precision of the dataset in advance, set the slider step to the number precision (e.g. `min value of the range = 0.11`, `max value of the range = 3.345`, `step value = 0.001`)

2) if you are not fully aware of the precision you can round down the min value to the first integer less than the min value itself and round up the maximum value of the range to the next integer. In this case the range on the filter is grater than the real range of the dataset but this ensure the visibility of all the data.

Of course there is a third way represented by the combination of the two solution above, but you have to choose an arbitrary precision for the value of the step.

Hope this helps

R

**Comment by tethysgeco** [comment]
Hi @mind84, thanks for all the details and ideas you shared.
We have checked some more data and situations where numeric filter can be used and we have this additional information:
•	Many times, we are not aware in advance of the maximum decimal digits that will be used in the datasets because data will be updated during time and the precision of measurements can change over time for the same variable
•	Sometimes the environmental parameter involved in numeric filter can vary between 0 to 1 (for example between 10-7 and 10-2)
Thus, given that the problem seems to be correlated with the need to set the step of the slider,  the most complete solution could be reading max and min values (already available) and the max number of decimal digits directly from the dataset to set the slider? Also in the case that this optimization could be done, in some situations the slider could become unmanageable (e.g. when the max number of decimal digits is too little with respect to the difference between max and min values)? Maybe another solution could be to find an alternative to the use of the slider?

**Comment by mind84** [comment]
Hi @tethysgeco,

> Thus, given that the problem seems to be correlated with the need to set the step of the slider, the most complete solution could be reading max and min values (already available) and the max number of decimal digits directly from the dataset to set the slider?
 
yes, the max number of digits can be read by JavaScript when initializing the slider and the step can be set according to this value.

> Also in the case that this optimization could be done, in some situations the slider could become unmanageable (e.g. when the max number of decimal digits is too little with respect to the difference between max and min values)?

I think this depends on how your users intend to use the filter. Generally speaking, I wouldn't worry about unmanageability. If I'm not totally wrong user can enter the range values in the two textboxes above the slider and so the range can be adjust by acting on these textboxes. Beside that, do you see limitation/problems or any user experience issues on this behavior that I'm missing?

> Maybe another solution could be to find an alternative to the use of the slider?

No, i think not. I guess that the slider is the best option for this purpose.

Regards

R

**Comment by aeduard** [comment]
This issue with default integer values for slider persists also in version 3.7.x. The second slider is not working.

![slider_lizmap](https://github.com/3liz/lizmap-web-client/assets/16295364/54a7bbd0-b8c6-4349-8ddb-41047a13a7ec)

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
