### ISSUE TITLE
[Bug]: form filter doesn't work proprely if ID value is not properly specified

### ISSUE THREAD

**Issue by bsaglio2001** [3liz/lizmap-web-client#3967]
### What is the bug?

Not exactly sure it's a bug... I share my experience anyway.

I'd tried to add a PostGIS view in my project and then apply dynamic filters to this layer using several attributes.

First, I created this PostGIS view with a SQL code like this : 
`SELECT row_number() OVER (ORDER BY o.annee, o.producteur, o.nomvernacu, o.groupe) AS vid`
Then the behaviour of form filters in Lizmap Web Client is pretty unpredictable. The number of entities is correct but the corresponding entities (displayed in the map or in the datatable view) are not the good ones (ie those with values selected in form filter).

Then, I recreated this PostGIS view using the ID provided with the tables referenced by the view.
Thus form filters work correctly in Lizmap Web Client.

### Steps to reproduce the issue

1. Create 2 similar views in a PostGreSQL/PostGIS database, with an ID attribute based on ;

- ROW_NUMBER() function for the first one
- the ID attribute of the referenced tables in the second one

3. Load these 2 views in a QGS project and configure form filters applying to both.

4. Check the dynamic result in Lizmap Web Client.
 

### Versions

**Versions :**

* Lizmap Web Client : 3.6.7
* Lizmap plugin : 3.18.1
* QGIS Desktop : 3.28.11
* Lizmap.com : Yes
* QGIS Server : 3.28.11
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.18.1
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

WIndows 10

### Browsers

Firefox

### Browsers version

Version 119.0.1 (32 bits)

**Comment by Gustry** [comment]
Using `row_number` is not recommended at all, as QGIS server needs a proper primary key if possible

2 things : 

* QGIS server will create a temporary primary key because none is defined in your view
* row_number is not a stable ID, you have many different QGIS server running, launching each different SELECT over your view, so returning different row number ID (one QGIS server could answer for one part of the map, the other one for the attribute table, another one for the other part of the map)


CC @mdouchin
