### ISSUE TITLE
Disable/remove abstract on mouse over

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#428]
![screenshot_20161209_163919](https://cloud.githubusercontent.com/assets/1951107/21056590/27e51ac2-be2e-11e6-9da6-a60e4e27b35d.png)

Not sure I'm not seeing a proper option for the following request, if yes please disregard and close this ticket.

See above image:
as the abstract is now available in a very convenient way using the "information" button, showing the same automatically when passing the mouse pointer over the layer name seems to no more necessary, also because it does not fits well long abstracts.

As an addition also an option to disable "information" for groups would be nice, as not always they have any info to be shown.

This also is related to https://github.com/3liz/lizmap-web-client/issues/244 

cheers!

**Comment by mdouchin** [comment]
I agree since we recently open the sub dock panel any time a user clicks on the layer/group name in the legend, there is no real need to display the abstract on hover.

Obviously we should also improve the subdock CSS to allow scrolling, in case the abstract is looooong like yours ;)
By the way, I have never tried to use HTML in the abstract, but basic tags such as <p>, <b>, <u> and <li> shoud render properly

**Comment by rldhont** [comment]
Fix in 8466ebc9ee7d20a917e0681bbf9b9a07dc6cce9b

**Comment by RobiFag** [comment]
Hi all,
maybe I haven't understood but it's not clear to me how to remove or even better change the text of the tooltip that is shown when the mouse passes over the layer name in the layer tree.
I'have tried with a js file like this:
`
lizMap.events.on({
   mouseover: function() {
      $("div#content div#switcher.tab-pane div#switcher-layers-container.switcher div.menu-content div#switcher-layers div.without-blocks.no-group table.tree.treeTable tbody tr td div.tooltip div.tooltip-inner:contains('some text')").html('new text');
   }
});
`
It doesn't work, maybe the problem is the mouseover event, I have also tried with some available lizmap events but they don't work too.

Any idea about how to manage the tooltip event?

Thanks!
