### ISSUE TITLE
Instruction for Redis cache

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4324]
### What is the question? (in English)

Where can I find instructions to install and configure Redis for Ubuntu, and configure it for LWC?

### Versions, safeguards, check summary etc

LTR on all

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

LTR

**Comment by Antoviscomi** [comment]
I just googled i.e. [(https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-22-04)] and install and configure it, after enabling redis-server as systemd process `sudo systemctl enable redis-server`, and start it `sudo systemctl start redis-server` , test if it's working throug `redis-cli` in a terminal

![Schermata del 2024-03-25 16-51-53](https://github.com/3liz/lizmap-web-client/assets/12639444/7cd67a84-44e0-495e-ba76-4e9078e5465d)

then, in order to make redis working as LWC cache server, you only need to set it in LWC Admin Panel, under Lizmap Configuration as in screenshot inserting your own path and folder

![Schermata del 2024-03-25 16-46-53](https://github.com/3liz/lizmap-web-client/assets/12639444/0a034f69-e680-4068-90c6-d603daf4c610)

**Comment by katagen** [comment]
And also need php-redis I supposed? Or not?

**Comment by Antoviscomi** [comment]
@katagen i've installed only the required dependecies and works fine for me

**Comment by Antoviscomi** [comment]
And php-redis it's required to be able to run LWC scripts like console.php i.e.

**Comment by katagen** [comment]
OK, perfect!

**Comment by katagen** [comment]
Perfect!
