### ISSUE TITLE
[Bug]: values in relation tables are not sorted alphabetically

### ISSUE THREAD

**Issue by InnovPlantProtect** [3liz/lizmap-web-client#4419]
### What is the bug? (in English)

I have a table in postgresql which has several tables related to it. Each of these tables are lists and their values need to be sorted alphabetically to facilitate the data input. In QGIS if i edit the table and add a new records, then the values of the lists appear sorted. However, when i publish the project in lizmap and i add a new record, these values do not appear in alphabetical order anymore. 

### Steps to reproduce the issue

Upload a table from postgres with related tables (lists). 
Check that the related tables (lists) are mapped in the form (see screenshot below)
![table_property](https://github.com/3liz/lizmap-web-client/assets/73950278/97cded7c-ead7-470d-a5e6-d21a186522e6)
Then publish the project in lizmap.
In lizmap open the form and add the values. As showed below the values are not sorted
![IMG20240508145557_cropped](https://github.com/3liz/lizmap-web-client/assets/73950278/e4392b86-8f59-4032-a7cb-3772545ed63b)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.9
* Lizmap plugin : 4.3.1
* QGIS Desktop : 3.34.6
* QGIS Server : 3.34.5
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22

### Browsers

Firefox, Chrome

### Browsers version

recent

**Comment by gioman** [comment]
@Gustry possibly related to https://github.com/qgis/QGIS/pull/52249

**Comment by gioman** [comment]
@Gustry Can we have some feedback here? If necessary we can revert the commit in QGIS that apparently caused this regression (if we have understand well the problem).

**Comment by Gustry** [comment]
I don't know, I was just adding a label for triaging.

**Comment by gioman** [comment]
> Sorry, I don't know, I was just adding a label for triaging.

@Gustry this turns out to be a problem in LMWC: since the option "sort by value" was removed

https://github.com/qgis/QGIS/pull/52249

in QGIS xml is not written anymore "orderByValue" so your code

https://github.com/3liz/lizmap-web-client/blob/f7c0c7de15f06439f4ab52f0c9079fc0c40e83da/lizmap/modules/lizmap/lib/Form/QgisForm.php#L1764C1-L1767C14

does not do any ordering anymore. It is still unclear (we are trying to understand it) why in QGIS desktop form the order is presented alphabetical and not natural as for that specific widget it seems there is no code for ordering (but probably there is, otherwise it is not explained how).

Regardless... seems to make sense for LMWC to present the order in alphabetical/ascending way, as it is the most common use case. We are still considering in re-adding that option and make it work properly, so if is unchecked it will use foreign key order, if is checked it will use alphabetical/ascending as it already happen for the value relation type of widget (where all this mess apply is for relation reference).

**Comment by Gustry** [comment]
@gioman I don't know all implications of this change. I think having a default alphabetical order makes sense, so go for it to try. You can do it straight from GitHub and run the test suite on the PR, so we can see if it's breaking some tests.

**Comment by gioman** [comment]
> @gioman I don't know all implications of this change. I think having a default alphabetical order makes sense, so go for it to try. You can do it straight from GitHub and run the test suite on the PR, so we can see if it's breaking some tests.

just did it, finger crossed.
