### ISSUE TITLE
Notes on the 3.10.0 pre

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4920]
Is it still too early to comment on the future 3.10.0?
I noticed two things during the first installation (3.10.0-pre from 24.10.2024, QGIS 3.34.11):
https://cx21-10.webgis.biz

- I find the card management in the backend too confusing (what happens with many groups?):
V3.10.0-pre
![image](https://github.com/user-attachments/assets/80e1e48c-1dda-4799-9a0d-3ab5b74d9918)

V3.9.0-pre
![image](https://github.com/user-attachments/assets/2d8cc9a9-b54b-45f4-b846-8fb1f5e222d5)

- The window for theme selection is too small:
V3.10:
![image](https://github.com/user-attachments/assets/c841dccc-7c9f-44b8-b9d9-637fe153754e)

V3.9:
![image](https://github.com/user-attachments/assets/b4c2b273-cfd2-4f34-b300-9c9bfc7cadfb)

additional suggestion:
I would find it helpful if the current theme is displayed next to the eye. (if the name is too long you could also cut it off)
![image](https://github.com/user-attachments/assets/95d2ee1d-3929-4310-8688-d377764cd3d8)

otherwise initial tests are working quite well :)

**Comment by Gustry** [comment]
Hi @guenterw 

Thanks for your early testing of the 3.10 version.

The only difference between LWC 3.9 and LWC 3.10 is the migration from Bootstrap 2 to Bootstrap 5.
https://getbootstrap.com/

This migration brought a major break in the UI, so all your issues are related to this new version of Bootstrap. That's why also LWC 3.9 branch was created early and we have two dev branches for now.

All your issues you have reported were not made on purpose, just a consequence.

**Comment by guenterw** [comment]
Hi @Gustry, thanks for the feedback and explanation
