### ISSUE TITLE
Edition - keep form open after saving

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#594]
In some cases, it would be great to go back to the editing form after the creation of modification of a feature, for example when working with child tables ( e.g. roads and road works). This would facilitate the workflow: 
1/ create or modify road -> 2/ add child work
instead of 
1/ create or modify road -> 2/ re-click on road to open popup 3/ click on the edit (pen) button in the popup to open the editing form 3/ add child work

Proposal : Add a new submit button called "Save and reopen form"

**Comment by jlstanus** [comment]
Too much buttons kills the ergonomy 🈂️

**Comment by rldhont** [comment]
@jlstanus can you test https://github.com/3liz/lizmap-web-client/pull/693 and give us feedbacks ?

**Comment by jlstanus** [comment]
I did some tests on the lizmap-web-client-master-edition-32 from @rldhont  repository
But cannot go very far because of a problem with WFS. Of course, the checkbox is checked. No problem with the same project in 3.1.4 . I cannot access to the attribute table.
Something goes wrong with wfs 

![image](https://user-images.githubusercontent.com/402354/33365734-72142fde-d4e9-11e7-8955-bafe49183797.png)
![image](https://user-images.githubusercontent.com/402354/33365795-a3e59502-d4e9-11e7-8569-20ee03978d30.png)
![image](https://user-images.githubusercontent.com/402354/33365865-dfc0ca6a-d4e9-11e7-8f98-5ec264ce64cc.png)
![image](https://user-images.githubusercontent.com/402354/33365903-03f87522-d4ea-11e7-9e9d-736a5f7384ab.png)

**Comment by rldhont** [comment]
@jlstanus What the print screen explains ?
* The first seems to open the right  form, isn't it ?
* What is it happened in the second screen ?
* Has the geometry disappeared in the third ?

**Comment by jlstanus** [comment]
> What the print screen explains ? 

It explains that i cannot do some test with edition controller because WFS access is buggy in lizmap-web-client-master-edition-32. Search by location, attibutes table doesn't works. 

The edition mode in 3.1.5 is working well with edition and other WFS feature access.

> The first seems to open the right form, isn't it ?

Yes, it works in  lizmap-web-client-master-edition-32

> What is it happened in the second screen ?

I clicked on a polygon geometry to display attributes in the dock. But the WFS error message appears. This layer can only be edited.

> Has the geometry disappeared in the third ?

In the third, i use an other layer to create new point geometry. What is strange is that LWC knows the attributes fields in opposite to the layer with polygon geometry where it cannot be read. The but with point geometry is that new feature cannot be created.
