### ISSUE TITLE
pg_service.conf doesn't work for editing

### ISSUE THREAD

**Issue by tudorbarascu** [3liz/lizmap-web-client#620]
Hi,

Just installed Lizmap and it's working great except for editing postgres layers using pg_service.conf.

I get
```
[8]	Undefined index: host	/var/www/lizmap-web-client-3.1.2/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	144

error	2017-06-16 10:24:36	[402]	error during the connection %s	/var/www/lizmap-web-client-3.1.2/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	144
```

I have setup the PGSERVICEFILE variable in apache and the Map is working.

How can I point PHP to pg_service.conf?

I also want to document this as it's lacking in the lizmap docs.

PS. I also tried with PGSERVICE dir in  fcgid.conf and in env.conf to no avail.
Debian stretch - php 7 - lizmap-web-client-3.1.2

**Comment by mdouchin** [comment]
This issue must be solved inside lizmap for the editing of postgres layers.

**Comment by rldhont** [comment]
@mdouchin has been this issue fixed?

**Comment by mdouchin** [comment]
In master, but I am not sure this has been backported.

**Comment by rldhont** [comment]
do you know the commit ?

**Comment by mdouchin** [comment]
https://github.com/3liz/lizmap-web-client/commit/a9d73f100b41b640b73614a988a0ff561074b2b0

**Comment by zoidable** [comment]
Hi,

since upgrading to 3.2.1 (from 3.1), I seem to get the same error as the OP describes. Aside from editing, also the selection of geometries and opening the attribute table aren't working if the layer in question uses a PG SERVICE file. Layers using a regular pg connection are just working fine. The error message is: 

> [402]	error during the connection example	C:\Webserver\lizmap\prod\master\lib\jelix\plugins\db\pgsql\pgsql.dbconnection.php	153

I tried clean_vartmp and running the installer.php, but nothing changed. In Apache, the PGSERVICEFILE env is set via SetEnv and FcgidInitialEnv.

Anyone else experiencing this issue?

**Comment by rldhont** [comment]
Hi @zoidable,

You also have to update the PHP environnement.

You can put your `pg_service.conf` file to `/etc/postgresql-common/` directory to be used by all the softwares.

**Comment by zoidable** [comment]
Thanks @rldhont, I only set the environment variable within the QGIS Server virtual host, so PHP didn't get it...
