### ISSUE TITLE
delete related features from popup - "no object has been found at this location" -> close popup

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#682]
hi,

in case of deletion of related features from popup, the following message appears at the end of the process: 
"no object has been found at this location"

this issue is related to this other https://github.com/3liz/lizmap-web-client/issues/525

thanks

**Comment by josemvm** [comment]
would it be possible to test and fix this issue to make the process cleaner?

**Comment by rldhont** [comment]
I have to be OK with @mdouchin about the solution!
If you use popup on the map, the popup is removed.
If you use popup in the dock, the message is displayed because the click is repeated and the popup dock stayed alive with the last getfetaureinfo content. This has to be fixed the right way for all the getfeatureinfo request!

**Comment by josemvm** [comment]
nice! thanks

**Comment by rldhont** [comment]
@josemvm can you test it ?

**Comment by josemvm** [comment]
clean!!!

thanks a lot @rldhont
:-)
