### ISSUE TITLE
edition on spatialite database - Montpellier-Transports case

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#740]
i'm trying to edit layers (Editon layers group) from Montpellier project but the Edition icon doesn't appear in the left vertical menu bar

running  the `php7.0 -m|grep sqlite` command:
>[PHP Modules] 
pdo_sqlite
sqlite3

my lizmap error.log:

> 2018-01-08 11:30:30     10.27.11.245    error   Spatialite is not available

rights to the directory containing spatialite databases:

> 16259 -rwxrwxrwx 1 www-data www-data 4291584 Jan  3 14:48 edition_db.sqlite
16260 -rwxrwxrwx 1 www-data www-data 4733952 Jan  3 14:48 transport.sqlite

what is missing here (ubuntu installation)?

thanks in advance

**Comment by rldhont** [comment]
To use editing on layers spatiatlite, you have to add the spatialite extension in PHP.
https://docs.3liz.com/en/install/linux.html#spatialite

**Comment by josemvm** [comment]
hi @rldhont 

i had already seen the lizmap documentation. the documentation refers to php 5

in php 7 the extension is loaded by default if it is installed, as you can see above at `php7.0 -m|grep sqlite` command output

if i try to force the extension at "Dynamic Extensions"/extension= or "Module Settings"/[sqlite3] in php.ini file, i get this warning in php log file

> [08-Jan-2018 13:15:06 Europe/Paris] PHP Warning:  Module 'sqlite3' already loaded in Unknown on line 0

it's a little weird... it seems that lizmap can't

`// Check ability to load spatialite extension`

so

`// And remove ONLY spatialite layers if no extension found`
...

**Comment by rldhont** [comment]
It's not a PHP configuration but an SQLite3 configuration in PHP. You have to set the SQLite3 extension directory and add the file `libspatialite.so` or `mod_spatialite.so` in the defined directory like `/var/www/sqlite3_ext`.

**Comment by josemvm** [comment]
sorry for the noise... this is not a issue directly related to lizmap

my steps:

install package containing the `mod_spatialite.so` lib

create `/var/www/html/sqlite3_ext` directory

copy lib from `/usr/lib/x86_64-linux-gnu/` to `/var/www/html/sqlite3_ext/`

configure php.ini file
`[sqlite3]`
`sqlite3.extension_dir = /var/www/html/sqlite3_ext/mod_spatialite.so`

restart the apache server
![imagem](https://user-images.githubusercontent.com/10053874/34679197-1c77b83e-f48d-11e7-92ea-b9c86ce42637.png)

the problem remains

> 2018-01-08 16:52:32     10.27.11.245    error   Spatialite is not available

**Comment by josemvm** [comment]
it was my mistake

`[sqlite3]`
`sqlite3.extension_dir = /var/www/html/sqlite3_ext`
 instead of
`[sqlite3]`
`sqlite3.extension_dir = /var/www/html/sqlite3_ext/mod_spatialite.so`

thanks @rldhont

**Comment by zlanich** [comment]
@josemvm @rldhont Hey there, I've been struggling for DAYS trying to get Spatialite working through the built-in pdo_sqlite that comes with php7.2 on Debian, and I can't for the life of me find a solution. Did you get this working? 

Here's what I'm doing:

- Installed php 7.2 through `apt-get`
- Set ini's `sqlite3.extension_dir=/var/www/sqlite3_ext` (shows up in `phpinfo()`)
- `apt-get install libsqlite3-mod-spatialite`
- Copy `/usr/lib/x86_64-linux-gnu/mod_spatialite.so.7.1.0` to `/var/www/sqlite3_ext/mod_spatialite.so`
- `chmod +wrx /var/www/sqlite3_ext/mod_spatialite.so` Just to make sure it can read/execute it
- Call `SELECT spatialite_version();` in sql - Error: `no such function: spatialite_version`
- Call `(new \SQLite3(':memory:'))->loadExtension('mod_spatialite')` obviously fails because php's SQLite is compiled with the `SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION` option off by default
- Call `SELECT load_extension('mod_spatialite');` in sql obviously fails for the same reason.

We've also tried specifying a just dsn driver when creating the PDO Connection, and it just says driver not found. I may be doing it wrong, but I've tried everything I can think of.

I have to get Spatialite working via pdo_sqlite "somehow" for unit-testing our geo-application built in Laravel. Thoughts?

Anyone's help would be greatly appreciated. I'm really really stuck here. Thanks!

**Comment by zlanich** [comment]
UPDATE: So I was able to load it using a raw `SQLite3` instance it like so: 
```
use Brick\Geo\Engine\GeometryEngineRegistry;
use Brick\Geo\Engine\SQLite3Engine;
//...
$sqlite3 = new \SQLite3(':memory:');
$sqlite3->loadExtension('mod_spatialite.so');
GeometryEngineRegistry::set(new SQLite3Engine($sqlite3));
dd($sqlite3->query("SELECT GeomFromText('POINT(10 20)');")->fetchArray()); // Success
```

The issue is that Laravel relies on PDO and there's no way (that I know of) to actually call `->loadExtension('mod_spatialite.so');` using `pdo_sqlite`, so you have to use `SELECT load_extension('mod_spatialite');`, which is definitely disabled since I get an `unauthorized` error.

I'm even open to somehow recompiling php 7.2 without that `SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION` flag, but I'm not sure where to start because I honestly have no idea "how" SQLite is compiled into php (since it's included out of the box in Debian).

**Comment by rldhont** [comment]
@zlanich can you provide some changes to the documentation https://github.com/3liz/lizmap-documentation thanks

**Comment by rldhont** [comment]
@nboisteault this part of the comment has to be added to the documentation

> 
> Here's what I'm doing:
> 
>     * Installed php 7.2 through `apt-get`
> 
>     * Set ini's `sqlite3.extension_dir=/var/www/sqlite3_ext` (shows up in `phpinfo()`)
> 
>     * `apt-get install libsqlite3-mod-spatialite`
> 
>     * Copy `/usr/lib/x86_64-linux-gnu/mod_spatialite.so.7.1.0` to `/var/www/sqlite3_ext/mod_spatialite.so`
> 
>     * `chmod +wrx /var/www/sqlite3_ext/mod_spatialite.so` Just to make sure it can read/execute it
>

**Comment by tzanetti** [comment]
As anyone the same issue with the windows installation ?
I have a similiar notification in the lizmap error.log : 

2019-05-13 10:29:05	::1	error	Spatialite is not available
2019-05-13 10:29:06	::1	error	 erreur clé C:\webserver\webapp\prod2/opus1.qgs , limité à 255 caractères et seuls les caractères alphanumeric et le caractère '_' sont autorisés
2019-05-13 10:29:06	::1	warning	2019-05-13 10:29:06	[2]	openlog() expects parameter 3 to be integer, string given	C:\webserver\lizmap\prod\lizmap-web-client-3.1.12\lib\jelix\core\log\jSyslogLogger.class.php	34

I have followed this tutorial for the lizmap installation : 
https://opengislab.com/blog/2018/7/7/updated-installing-apache-qgis-server-and-lizmap-on-windows-os

Thanks in advance

**Comment by claudiogeop** [comment]
tzanetti 
Did you manage to solve this?
I have the same error in my lizmap error.log
