### ISSUE TITLE
value by default in postgresql table does not appear in lizmap

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#75]
the value by default in postgresql table does not appear in lizmap but work fine in qgis

**Comment by jancelin** [comment]
works well, thanks

**Comment by mdouchin** [comment]
@jancelin Can you test again with your view (described above) in Lizmap release_3_0 by commenting this line ? 
https://github.com/3liz/lizmap-web-client/blob/release_3_0/lizmap/modules/lizmap/controllers/edition.classic.php#L1163

I tried it myself with a very simple view, and this is not needed anymore since some further modifications in the edition code. Grabing default values representation from PostgreSQL and putting it in the form leads to side effects such as #417

**Comment by mdouchin** [comment]
ping @jancelin ;)

**Comment by rldhont** [comment]
Reopened if a9cd647bcc33583fd9b0afc86ed2d9b86e9f7367 not help

**Comment by jancelin** [comment]
I test in January, désolé du retard mais je sème mon orge de brasserie.

**Comment by jancelin** [comment]
hi,
I just tested with version 3.1beta4
* The default value for the integer works well.
* The default value for a relational value on a table edition is OK
* The default value for a relational value on a View edition  is not available, The same if we edit the default value of qgis.

![test_formulaire_-_demo_-_lizmap_-_2017-01-10_14 51 38](https://cloud.githubusercontent.com/assets/6421175/21808619/5636be74-d744-11e6-9237-cc1b806c7862.png)
![test_formulaire_-_demo_-_lizmap_-_2017-01-10_14 50 50](https://cloud.githubusercontent.com/assets/6421175/21808620/5637902e-d744-11e6-972b-1a7513c42739.png)
