### ISSUE TITLE
Range map scale with baselayer OSM

### ISSUE THREAD

**Issue by adelchia** [3liz/lizmap-web-client#843]
Good evening. I use lizmap 3.1.11 and Qgis 2.18.  I set in lizmap plugins, map options, a map scale of 900.000. When I enable baselayer OSM, the scale interval in the webgis project is between 18.056 and 57.7791. I want to see the whole project and so I need a scale equal to 700.000. Is there a way to do it?
Thank you.

**Comment by adelchia** [comment]
Sorry, I use lizmap 3.1.8

**Comment by gioman** [comment]
@adelchia short answer: it depends. If you use baselayers from tiled services (osm, google, bing, etc), your qgis project will be automatically set to EPSG:3857 (because you can't reproject such layers) and you are locked to the following levels/scales:

20 : 1128.497220
19 : 2256.994440
18 : 4513.988880
17 : 9027.977761
16 : 18055.955520
15 : 36111.911040
14 : 72223.822090
13 : 144447.644200
12 : 288895.288400
11 : 577790.576700
10 : 1155581.153000
9  : 2311162.307000
8  : 4622324.614000
7  : 9244649.227000
6  : 18489298.450000
5  : 36978596.910000
4  : 73957193.820000
3  : 147914387.600000
2  : 295828775.300000
1  : 591657550.500000

Workaround: add such layers not as baselayers in Lizmap but as WMS layers in QGIS. See for example: http://www.gdal.org/frmt_wms.html

**Comment by adelchia** [comment]
@gioman Ok, thanks a lot.  I looked the link. It's not an easy solution for me but I'll try.
