### ISSUE TITLE
Configuration should not mix static and dynamic configuration

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#856]
Lizmap should not store runtime data in the same config files  as static config. 

This lead to unecessary complexity when trying to re-deploy or upgrade lizmap installation with predefined configuration:  like module configuration - This makes Lizmap not Docker/Container  friendly.

**Comment by Gustry** [comment]
I think I got this issue too.
I was using https://github.com/3liz/lizmap-docker but the code of lizmap is included in the image. I wanted a dev environment with the code mounted in the container (easier to checkout a specific branch etc). I started my own dockerfile, but I got some issues because the configuration relies on files which are included in lizmap itself so it was not easy to have the image working without having the code of lizmap included in the docker image.

**Comment by rldhont** [comment]
@dmarteau Which lizmap conifg is static and dynamic ? In which file is lizmap mixing static and dynamic config ?

**Comment by dmarteau** [comment]
Exemple: the file localConfig.ini.php contains module configuration which is static: i.e the configuration is defined at launch-time. But this file contains also, run-time configuration set from the lizmap client user configuration (hash for credentials). 

Configuration set from the interface is set by the lizmap admin user, the configuration for module is set usually by the sysadmin, these are two different roles, and configuration set at runtime must not be mixed  with configuration set server side.
