### ISSUE TITLE
GWC and Geoserver not accepting WMS/WMTS fron Lizmap?

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#952]
Hi!

I am trying to use a WMW generated by Lizmap on Goesrever and is not working. Geowebcache crashes when inserting the WMS link from Lizmap. This is the link fron my Lizmap: 

http://qgis.nacka.se/index.php/lizmap/service/?repository=nackasbakgrund&project=nackasbakgrund&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

It works well on QGIS desktop. Any adea on what may be wrong?

Regards and thanks for a great product!
Abel Gonzalez

**Comment by rldhont** [comment]
Do you have some logs of GeoServer or GeoWebCache to know why, the GetCapabilities document is wrong for us ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.

**Comment by mariemgeo** [comment]
Hello,

I am reopening this post because I am encountering the same issue.

The GeoServer logs indicate
`ERROR [data.ows] - Failed to execute request https://www.lizmapURL`

I have correctly configured the usernames and passwords to access the project.

I have modified the Lizmap directory settings to allow my GeoServer's URL to access the WMS stream without success.

I don't think it comes from GeoServer, as I already have some WMS set up that are working.

Thank you for your response.

**Comment by gioman** [comment]
> `ERROR [data.ows] - Failed to execute request https://www.lizmapURL`

@mariemgeo that URL seems really wrong.

**Comment by mariemgeo** [comment]
I provided an example URL. I did not want to include the actual URL of my Lizmap project. 
However, regarding the Geoserver logs, I only have what I mentioned in my last message."

**Comment by rldhont** [comment]
@mariemgeo I found this https://stackoverflow.com/questions/78543316/geoserver-connection-to-external-wms-fails
and this GeoServer error message is more about a restriction du to a proxy to access the lizmap server than an issue in lizmap server.

**Comment by mariemgeo** [comment]
If I understand correctly, the issue is more on the Geoserver side (restriction) than on the Lizmap side?
